/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/profiles/{profileId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * public-profile用participant credentialを発行する
         * @description server profileのAuthorization Modeがpublic-profileの場合だけ利用できる。
         *     browser profile UUIDと配備originへcredentialを束縛し、他modeへfallbackしない。
         */
        post: operations["createFeedbackParticipant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 公開profileと利用可能operationを取得する */
        get: operations["getFeedbackProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 認可済みworkspaceを列挙する */
        get: operations["listFeedbackWorkspaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/workspaces/{workspaceId}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 認可済みresource候補を列挙する */
        get: operations["listFeedbackResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/workspaces/{workspaceId}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** scope内のthreadを安定順序で取得する */
        get: operations["listFeedbackThreads"];
        put?: never;
        /**
         * threadと最初のmessageを作成する
         * @description 最初のprovider writeへthreadId、intentId、requestHashを同時保存する。
         */
        post: operations["createFeedbackThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/workspaces/{workspaceId}/threads/{threadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** thread詳細を取得する */
        get: operations["getFeedbackThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/workspaces/{workspaceId}/threads/{threadId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** threadへreplyを追加する */
        post: operations["replyFeedbackThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/workspaces/{workspaceId}/threads/{threadId}/messages/{messageId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 自分のmessageへrevisionを追加する */
        post: operations["appendFeedbackRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/workspaces/{workspaceId}/threads/{threadId}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 独立権限でattachmentをstream uploadする
         * @description 結果不明時に同じbinaryを自動再送しない。
         */
        post: operations["uploadFeedbackAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/workspaces/{workspaceId}/threads/{threadId}/attachments/{attachmentId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** attachmentをstream downloadする */
        get: operations["getFeedbackAttachment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/workspaces/{workspaceId}/intents/{intentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** providerを正本として操作結果を回収する */
        get: operations["recoverFeedbackIntent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StableKey: string;
        /** Format: uuid */
        StableId: string;
        RequestHash: string;
        /** @description version、query fingerprint、stable ordering boundaryへ束縛したopaque token */
        Cursor: string;
        /** @enum {string} */
        Operation: "feedback:read" | "feedback:create" | "feedback:reply" | "feedback:revise" | "feedback:attachment:read" | "feedback:attachment:upload";
        /** @enum {string} */
        OperationGuarantee: "recoverable" | "best-effort" | "unsupported";
        ResourceRef: {
            kind: components["schemas"]["StableKey"];
            key: string;
        };
        OrderingKey: {
            /** Format: date-time */
            occurredAt: string;
            eventId: components["schemas"]["StableId"];
        };
        WorkspaceSummary: {
            workspaceId: components["schemas"]["StableKey"];
            displayName: string;
        };
        ResourceSummary: {
            resource: components["schemas"]["ResourceRef"];
            displayName: string;
        };
        CreationFieldOption: {
            value: string;
            label: string;
        };
        CreationField: {
            key: components["schemas"]["StableKey"];
            label: string;
            /** @enum {string} */
            type: "text" | "date" | "select" | "reference";
            required: boolean;
            options?: components["schemas"]["CreationFieldOption"][];
        };
        Capabilities: {
            backendOperations: components["schemas"]["Operation"][];
            discovery: {
                /** @enum {string} */
                workspaces: "supported" | "unsupported";
                /** @enum {string} */
                resources: "supported" | "unsupported";
            };
            operationGuarantees: {
                create: components["schemas"]["OperationGuarantee"];
                reply: components["schemas"]["OperationGuarantee"];
                revision: components["schemas"]["OperationGuarantee"];
                attachmentUpload: components["schemas"]["OperationGuarantee"];
            };
            creationFields: components["schemas"]["CreationField"][];
            maximumAttachmentBytes: number;
            attachmentContentTypes: string[];
        };
        Profile: {
            /** @constant */
            schemaVersion: "2";
            profileId: components["schemas"]["StableKey"];
            displayName: string;
            capabilities: components["schemas"]["Capabilities"];
            /** @description 現在requestの認可結果、profile policy、backend capabilityの積集合 */
            effectivePermissions: components["schemas"]["Operation"][];
            /** @description 認可付きsame-origin相対path。provider URLではない */
            externalNavigationPath?: string;
        };
        ProfileResult: {
            profile: components["schemas"]["Profile"];
        };
        CreateParticipantRequest: {
            browserProfileId: components["schemas"]["StableId"];
        };
        ParticipantCredentialResult: {
            participantId: components["schemas"]["StableId"];
            credential: string;
        };
        WorkspacePage: {
            items: components["schemas"]["WorkspaceSummary"][];
            nextCursor: components["schemas"]["Cursor"] | null;
        };
        ResourcePage: {
            items: components["schemas"]["ResourceSummary"][];
            nextCursor: components["schemas"]["Cursor"] | null;
        };
        Author: components["schemas"]["ParticipantAuthor"] | components["schemas"]["ProviderAuthor"] | components["schemas"]["UnknownAuthor"];
        ParticipantAuthor: {
            /** @constant */
            kind: "participant";
            participantId: components["schemas"]["StableId"];
            displayName: string;
            /** @default false */
            isCurrentParticipant: boolean;
        };
        ProviderAuthor: {
            /** @constant */
            kind: "provider-user";
            displayName: string;
        };
        UnknownAuthor: {
            /** @constant */
            kind: "unknown";
            /** @constant */
            displayName: "Unknown";
        };
        Attachment: {
            attachmentId: components["schemas"]["StableId"];
            filename: string;
            contentType: string;
            sizeBytes: number;
            /** Format: date-time */
            createdAt: string;
        };
        MessageRevision: {
            revisionId: components["schemas"]["StableId"];
            body: string;
            /** Format: date-time */
            revisedAt: string;
            orderingKey: components["schemas"]["OrderingKey"];
        };
        Message: {
            messageId: components["schemas"]["StableId"];
            body: string;
            author: components["schemas"]["Author"];
            /** Format: date-time */
            createdAt: string;
            orderingKey: components["schemas"]["OrderingKey"];
            revisions: components["schemas"]["MessageRevision"][];
            attachments: components["schemas"]["Attachment"][];
        };
        ThreadSummary: {
            threadId: components["schemas"]["StableId"];
            resource: components["schemas"]["ResourceRef"];
            title: string;
            /** @enum {string} */
            status: "open" | "closed";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            messageCount: number;
        };
        Thread: components["schemas"]["ThreadSummary"] & {
            messages: components["schemas"]["Message"][];
        };
        ThreadPage: {
            items: components["schemas"]["ThreadSummary"][];
            nextCursor: components["schemas"]["Cursor"] | null;
        };
        ThreadResult: {
            thread: components["schemas"]["Thread"];
        };
        CreateThreadCommand: {
            intentId: components["schemas"]["StableId"];
            requestHash: components["schemas"]["RequestHash"];
            threadId: components["schemas"]["StableId"];
            resource: components["schemas"]["ResourceRef"];
            title: string;
            body: string;
        };
        ReplyCommand: {
            intentId: components["schemas"]["StableId"];
            requestHash: components["schemas"]["RequestHash"];
            messageId: components["schemas"]["StableId"];
            body: string;
        };
        AppendRevisionCommand: {
            intentId: components["schemas"]["StableId"];
            requestHash: components["schemas"]["RequestHash"];
            revisionId: components["schemas"]["StableId"];
            body: string;
            expectedRevisionId: components["schemas"]["StableId"];
        };
        UploadAttachmentCommand: {
            intentId: components["schemas"]["StableId"];
            requestHash: components["schemas"]["RequestHash"];
            attachmentId: components["schemas"]["StableId"];
            messageId?: components["schemas"]["StableId"];
            filename: string;
            contentType: string;
            sizeBytes: number;
            contentHash: components["schemas"]["RequestHash"];
            /** @enum {string} */
            purpose: "evidence" | "conversation";
        };
        /** @enum {string} */
        CommandDisposition: "created" | "recovered" | "already_applied";
        ThreadCommandResult: {
            disposition: components["schemas"]["CommandDisposition"];
            intentId: components["schemas"]["StableId"];
            thread: components["schemas"]["Thread"];
        };
        MessageCommandResult: {
            disposition: components["schemas"]["CommandDisposition"];
            intentId: components["schemas"]["StableId"];
            message: components["schemas"]["Message"];
        };
        AttachmentCommandResult: {
            disposition: components["schemas"]["CommandDisposition"];
            intentId: components["schemas"]["StableId"];
            attachment: components["schemas"]["Attachment"];
        };
        IntentRecoveryResult: components["schemas"]["IntentNotFoundResult"] | components["schemas"]["IntentPendingResult"] | components["schemas"]["IntentCompletedResult"] | components["schemas"]["IntentRepairRequiredResult"];
        IntentNotFoundResult: {
            intentId: components["schemas"]["StableId"];
            /** @constant */
            state: "not_found";
            operation: components["schemas"]["Operation"];
        };
        IntentPendingResult: {
            intentId: components["schemas"]["StableId"];
            /** @constant */
            state: "pending";
            operation: components["schemas"]["Operation"];
            retryAfterSeconds: number;
            /** @constant */
            automaticWriteAllowed: false;
        };
        IntentCompletedResult: {
            intentId: components["schemas"]["StableId"];
            /** @constant */
            state: "completed";
            operation: components["schemas"]["Operation"];
            stableResultId: components["schemas"]["StableId"];
        };
        IntentRepairRequiredResult: {
            intentId: components["schemas"]["StableId"];
            /** @constant */
            state: "repair_required";
            operation: components["schemas"]["Operation"];
            detail: string;
            /** @constant */
            automaticWriteAllowed: false;
            /** @enum {string} */
            retryDirective: "recover-only" | "manual-confirmation" | "do-not-write";
        };
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            /** @enum {string} */
            code: "feedback.invalid_request" | "feedback.unauthorized" | "feedback.forbidden" | "feedback.not_found" | "feedback.conflict" | "feedback.cursor_invalid" | "feedback.integrity_error" | "feedback.provider_unavailable" | "feedback.provider_timeout" | "feedback.authorization_unavailable" | "feedback.rate_limited" | "feedback.payload_too_large" | "feedback.unsupported_media_type" | "feedback.unsupported";
            detail?: string;
            traceId?: string;
            retryable: boolean;
            retryAfterSeconds?: number;
            conflict?: {
                expected?: string;
                actual?: string;
            };
        };
    };
    responses: {
        /** @description RFC 9457準拠の正規化error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ProfileId: components["schemas"]["StableKey"];
        WorkspaceId: components["schemas"]["StableKey"];
        WorkspaceIdQuery: components["schemas"]["StableKey"];
        ThreadId: components["schemas"]["StableId"];
        ThreadIdQuery: components["schemas"]["StableId"];
        MessageId: components["schemas"]["StableId"];
        AttachmentId: components["schemas"]["StableId"];
        IntentIdPath: components["schemas"]["StableId"];
        RequestHash: components["schemas"]["RequestHash"];
        /** @description same-originのunsafe requestへ固定値を付け、browserの単純cross-origin送信を拒否する。 */
        Csrf: "1";
        ResourceKind: components["schemas"]["StableKey"];
        ResourceKey: string;
        Cursor: components["schemas"]["Cursor"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createFeedbackParticipant: {
        parameters: {
            query?: never;
            header: {
                /** @description same-originのunsafe requestへ固定値を付け、browserの単純cross-origin送信を拒否する。 */
                "X-Feedback-CSRF": components["parameters"]["Csrf"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateParticipantRequest"];
            };
        };
        responses: {
            /** @description 発行したparticipant credential */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantCredentialResult"];
                };
            };
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    getFeedbackProfile: {
        parameters: {
            query: {
                workspaceId: components["parameters"]["WorkspaceIdQuery"];
                resourceKind: components["parameters"]["ResourceKind"];
                resourceKey: components["parameters"]["ResourceKey"];
            };
            header?: never;
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 公開profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    listFeedbackWorkspaces: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description workspace page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    listFeedbackResources: {
        parameters: {
            query?: {
                query?: string;
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                profileId: components["parameters"]["ProfileId"];
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description resource page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourcePage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    listFeedbackThreads: {
        parameters: {
            query: {
                resourceKind: components["parameters"]["ResourceKind"];
                resourceKey: components["parameters"]["ResourceKey"];
                order?: "updated_desc" | "updated_asc";
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                profileId: components["parameters"]["ProfileId"];
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description thread page。cursorはquery scopeへ束縛されたopaque token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    createFeedbackThread: {
        parameters: {
            query?: never;
            header: {
                /** @description same-originのunsafe requestへ固定値を付け、browserの単純cross-origin送信を拒否する。 */
                "X-Feedback-CSRF": components["parameters"]["Csrf"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateThreadCommand"];
            };
        };
        responses: {
            /** @description 既存結果を回収または既適用として解決した */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadCommandResult"];
                };
            };
            /** @description 新規threadを作成した */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadCommandResult"];
                };
            };
            /** @description 結果は未確定でありintent回収が必要 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentRecoveryResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    getFeedbackThread: {
        parameters: {
            query: {
                resourceKind: components["parameters"]["ResourceKind"];
                resourceKey: components["parameters"]["ResourceKey"];
            };
            header?: never;
            path: {
                profileId: components["parameters"]["ProfileId"];
                workspaceId: components["parameters"]["WorkspaceId"];
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description thread詳細 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    replyFeedbackThread: {
        parameters: {
            query: {
                resourceKind: components["parameters"]["ResourceKind"];
                resourceKey: components["parameters"]["ResourceKey"];
            };
            header: {
                /** @description same-originのunsafe requestへ固定値を付け、browserの単純cross-origin送信を拒否する。 */
                "X-Feedback-CSRF": components["parameters"]["Csrf"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
                workspaceId: components["parameters"]["WorkspaceId"];
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplyCommand"];
            };
        };
        responses: {
            /** @description reply操作結果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageCommandResult"];
                };
            };
            /** @description replyを作成した */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageCommandResult"];
                };
            };
            /** @description 結果は未確定でありintent回収が必要 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentRecoveryResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    appendFeedbackRevision: {
        parameters: {
            query: {
                resourceKind: components["parameters"]["ResourceKind"];
                resourceKey: components["parameters"]["ResourceKey"];
            };
            header: {
                /** @description same-originのunsafe requestへ固定値を付け、browserの単純cross-origin送信を拒否する。 */
                "X-Feedback-CSRF": components["parameters"]["Csrf"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
                workspaceId: components["parameters"]["WorkspaceId"];
                threadId: components["parameters"]["ThreadId"];
                messageId: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppendRevisionCommand"];
            };
        };
        responses: {
            /** @description revision操作結果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageCommandResult"];
                };
            };
            /** @description revisionを作成した */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageCommandResult"];
                };
            };
            /** @description 結果は未確定でありintent回収が必要 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentRecoveryResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    uploadFeedbackAttachment: {
        parameters: {
            query: {
                resourceKind: components["parameters"]["ResourceKind"];
                resourceKey: components["parameters"]["ResourceKey"];
            };
            header: {
                /** @description same-originのunsafe requestへ固定値を付け、browserの単純cross-origin送信を拒否する。 */
                "X-Feedback-CSRF": components["parameters"]["Csrf"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
                workspaceId: components["parameters"]["WorkspaceId"];
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    command: components["schemas"]["UploadAttachmentCommand"];
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description attachmentを回収または既適用として解決した */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentCommandResult"];
                };
            };
            /** @description attachmentを作成した */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentCommandResult"];
                };
            };
            /** @description 結果不明。binaryを自動再送せずintent回収または利用者確認が必要 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentRecoveryResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    getFeedbackAttachment: {
        parameters: {
            query: {
                resourceKind: components["parameters"]["ResourceKind"];
                resourceKey: components["parameters"]["ResourceKey"];
            };
            header?: never;
            path: {
                profileId: components["parameters"]["ProfileId"];
                workspaceId: components["parameters"]["WorkspaceId"];
                threadId: components["parameters"]["ThreadId"];
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description attachment content */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    recoverFeedbackIntent: {
        parameters: {
            query: {
                threadId: components["parameters"]["ThreadIdQuery"];
                operation: "feedback:create" | "feedback:reply" | "feedback:revise" | "feedback:attachment:upload";
                resourceKind: components["parameters"]["ResourceKind"];
                resourceKey: components["parameters"]["ResourceKey"];
            };
            header: {
                "X-Feedback-Request-Hash": components["parameters"]["RequestHash"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
                workspaceId: components["parameters"]["WorkspaceId"];
                intentId: components["parameters"]["IntentIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description intent回収状態 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentRecoveryResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
}
