/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/profiles/{profileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 公開profileとcapabilityを取得する */
        get: operations["getRedmineProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 認証済みprincipalを取得する */
        get: operations["getRedmineCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 認可済みresourceのthreadを一覧する */
        get: operations["listRedmineThreads"];
        put?: never;
        /** Redmine issueとして初回投稿を作成する */
        post: operations["createRedmineThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/threads/{threadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全journalとattachmentを含むthreadを取得する */
        get: operations["getRedmineThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/threads/{threadId}/attachments/{attachmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** thread所属確認済みattachmentを取得する */
        get: operations["getRedmineAttachment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HostResourceRef: {
            /** @constant */
            schemaVersion: "1";
            /** @enum {string} */
            kind: "record" | "page";
            key: string;
        };
        Perspective: {
            code: string;
            label: string;
        };
        CaptureProfile: {
            enabled: boolean;
            maximumUploadBytes: number;
            contentTypes: ("image/png" | "image/webp")[];
        };
        AttachmentProfile: {
            maximumInlinePreviewBytes: number;
            maximumDownloadBytes: number;
        };
        ClientProfile: {
            /** @constant */
            schemaVersion: "1";
            id: string;
            displayName: string;
            applicationKey: string;
            environmentKey: string;
            externalWorkspaceKey: string;
            perspectives: components["schemas"]["Perspective"][];
            capture: components["schemas"]["CaptureProfile"];
            attachments: components["schemas"]["AttachmentProfile"];
            showRedmineLink?: boolean;
        };
        Capabilities: {
            canRead: boolean;
            canCreate: boolean;
            /** @constant */
            repliesReadOnly: true;
            /** @constant */
            stateReadOnly: true;
        };
        ProfileResult: {
            profile: components["schemas"]["ClientProfile"];
            capabilities: components["schemas"]["Capabilities"];
        };
        Principal: {
            subjectId: string;
            displayName: string | null;
            redmineUserId: number | null;
            /** @enum {string} */
            source: "host-session" | "redmine-api-key";
        };
        CurrentUserResult: {
            principal: components["schemas"]["Principal"];
        };
        NamedValue: {
            id: number;
            name: string;
        };
        Locator: {
            /** @constant */
            v: "1";
            location: components["schemas"]["Location"];
            target: components["schemas"]["Target"] | null;
        };
        Location: {
            /** @constant */
            schemaVersion: "1";
            pageKey: string;
            routeTemplate: string;
            pathParameters: {
                [key: string]: string;
            };
            queryParameters?: {
                [key: string]: string;
            };
        };
        Target: components["schemas"]["UiElementTarget"] | components["schemas"]["ScreenPositionTarget"] | components["schemas"]["MapFeatureTarget"] | components["schemas"]["MapPositionTarget"];
        UiElementTarget: {
            /** @constant */
            schemaVersion: "1";
            /** @constant */
            kind: "ui-element";
            elementKey: string;
            relativeX: number;
            relativeY: number;
        };
        ScreenPositionTarget: {
            /** @constant */
            schemaVersion: "1";
            /** @constant */
            kind: "screen-position";
            relativeX: number;
            relativeY: number;
        };
        MapFeatureTarget: {
            /** @constant */
            schemaVersion: "1";
            /** @constant */
            kind: "map-feature";
            /** @constant */
            provider: "maplibre";
            sourceKey: string;
            sourceLayer?: string;
            featureKey: string;
            longitude: number;
            latitude: number;
        };
        MapPositionTarget: {
            /** @constant */
            schemaVersion: "1";
            /** @constant */
            kind: "map-position";
            longitude: number;
            latitude: number;
        };
        Attachment: {
            id: number;
            filename: string;
            byteSize: number;
            contentType: string | null;
            author: components["schemas"]["NamedValue"];
            /** Format: date-time */
            createdAt: string;
            inlinePreview: boolean;
            primaryEvidence: boolean;
        };
        Reply: {
            /** @constant */
            kind: "reply";
            journalId: number;
            body: string;
            author: components["schemas"]["NamedValue"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string | null;
        };
        Activity: {
            /** @constant */
            kind: "activity";
            journalId: number;
            /** @enum {string} */
            field: "status" | "assignee" | "priority" | "tracker" | "subject" | "description" | "attachment";
            oldValue: string | null;
            newValue: string | null;
            author: components["schemas"]["NamedValue"];
            /** Format: date-time */
            createdAt: string;
        };
        DiagnosticActivity: {
            /** @constant */
            kind: "diagnostic";
            journalId: number | null;
            message: string;
        };
        ThreadSummary: {
            /** Format: uuid */
            threadId: string;
            issueId: number;
            subject: string;
            initialComment: string;
            latestReply: string | null;
            status: components["schemas"]["NamedValue"];
            priority: components["schemas"]["NamedValue"] | null;
            assignee: components["schemas"]["NamedValue"] | null;
            author: components["schemas"]["NamedValue"];
            perspectiveCode: string | null;
            locator: components["schemas"]["Locator"] | null;
            hasAttachments: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Thread: {
            /** Format: uuid */
            threadId: string;
            issueId: number;
            subject: string;
            initialComment: string;
            latestReply: string | null;
            status: components["schemas"]["NamedValue"];
            priority: components["schemas"]["NamedValue"] | null;
            assignee: components["schemas"]["NamedValue"] | null;
            author: components["schemas"]["NamedValue"];
            perspectiveCode: string | null;
            locator: components["schemas"]["Locator"] | null;
            hasAttachments: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            description: string;
            tracker: components["schemas"]["NamedValue"];
            timeline: (components["schemas"]["Reply"] | components["schemas"]["Activity"] | components["schemas"]["DiagnosticActivity"])[];
            attachments: components["schemas"]["Attachment"][];
            /** Format: uri */
            redmineUrl: string | null;
            diagnosticCount: number;
        };
        ThreadListResult: {
            threads: components["schemas"]["ThreadSummary"][];
            nextCursor: string | null;
        };
        ThreadResult: {
            thread: components["schemas"]["Thread"];
        };
        CreateThreadRequest: {
            resourceRef: components["schemas"]["HostResourceRef"];
            /** Format: uuid */
            threadId: string;
            /** Format: uuid */
            intentId: string;
            comment: string;
            perspectiveCode: string;
            location: components["schemas"]["Location"];
            target: components["schemas"]["Target"] | null;
            release: string;
            locale: string;
            /** Format: date-time */
            capturedAt: string;
            evidence: components["schemas"]["EvidenceMetadata"] | null;
        };
        EvidenceMetadata: {
            filename: string;
            /** @enum {string} */
            contentType: "image/png" | "image/webp";
            byteSize: number;
            sha256: string;
            viewportWidth: number;
            viewportHeight: number;
            pixelRatio: number;
            /** Format: date-time */
            capturedAt: string;
        };
        Problem: {
            /** @enum {string} */
            code: "redmine.unauthenticated" | "redmine.invalid_api_key" | "redmine.permission_denied" | "redmine.not_found" | "redmine.duplicate_thread_id" | "redmine.thread_mismatch" | "redmine.content_type_rejected" | "redmine.payload_too_large" | "redmine.validation_failed" | "redmine.rate_limited" | "redmine.unavailable" | "redmine.contract_invalid" | "feedback.locator_too_large";
            message: string;
            retryable: boolean;
            upstreamStatus?: number | null;
            /** Format: uuid */
            requestId: string;
        };
        ProblemEnvelope: {
            /** @constant */
            ok: false;
            error: components["schemas"]["Problem"];
        };
    };
    responses: {
        /** @description sanitize済みproblem */
        Problem: {
            headers: {
                "Cache-Control": components["headers"]["NoStore"];
                "X-Content-Type-Options": components["headers"]["NoSniff"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemEnvelope"];
            };
        };
    };
    parameters: {
        ProfileId: string;
        ThreadId: string;
        AttachmentId: number;
        Origin: string;
        SecFetchSite: "same-origin";
        CsrfToken: string;
        IdempotencyKey: string;
        ResourceKind: "record" | "page";
        ResourceKey: string;
        PageKey: string;
        Sort: "created_desc" | "created_asc" | "updated_desc";
        StatusFilter: string;
        PerspectiveFilter: string;
        AssigneeFilter: number;
        PriorityFilter: number;
        QueryFilter: string;
        Cursor: string;
    };
    requestBodies: never;
    headers: {
        NoStore: "no-store";
        NoSniff: "nosniff";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRedmineProfile: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "Sec-Fetch-Site": components["parameters"]["SecFetchSite"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 公開profile */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    getRedmineCurrentUser: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "Sec-Fetch-Site": components["parameters"]["SecFetchSite"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description current principal */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    listRedmineThreads: {
        parameters: {
            query: {
                resourceKind: components["parameters"]["ResourceKind"];
                resourceKey: components["parameters"]["ResourceKey"];
                pageKey: components["parameters"]["PageKey"];
                sort: components["parameters"]["Sort"];
                status?: components["parameters"]["StatusFilter"];
                perspectiveCode?: components["parameters"]["PerspectiveFilter"];
                assigneeId?: components["parameters"]["AssigneeFilter"];
                priorityId?: components["parameters"]["PriorityFilter"];
                q?: components["parameters"]["QueryFilter"];
                cursor?: components["parameters"]["Cursor"];
            };
            header: {
                Origin: components["parameters"]["Origin"];
                "Sec-Fetch-Site": components["parameters"]["SecFetchSite"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description thread一覧 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadListResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    createRedmineThread: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "Sec-Fetch-Site": components["parameters"]["SecFetchSite"];
                "X-Feedback-CSRF": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    request: components["schemas"]["CreateThreadRequest"];
                    /** Format: binary */
                    evidence?: string;
                };
            };
        };
        responses: {
            /** @description 冪等回収した既存thread */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadResult"];
                };
            };
            /** @description 作成したthread */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            406: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    getRedmineThread: {
        parameters: {
            query: {
                resourceKind: components["parameters"]["ResourceKind"];
                resourceKey: components["parameters"]["ResourceKey"];
            };
            header: {
                Origin: components["parameters"]["Origin"];
                "Sec-Fetch-Site": components["parameters"]["SecFetchSite"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description thread詳細 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    getRedmineAttachment: {
        parameters: {
            query: {
                resourceKind: components["parameters"]["ResourceKind"];
                resourceKey: components["parameters"]["ResourceKey"];
            };
            header: {
                Origin: components["parameters"]["Origin"];
                "Sec-Fetch-Site": components["parameters"]["SecFetchSite"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
                threadId: components["parameters"]["ThreadId"];
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 検証済みattachment bytes */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    /** @description sanitize済みfilenameから生成したattachment disposition */
                    "Content-Disposition"?: string;
                    /** @description lowercase SHA-256 hex */
                    "X-Feedback-Content-SHA256"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                    "image/webp": string;
                    "application/octet-stream": string;
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            406: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
}
