/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** gateway processのlivenessを取得する */
        get: operations["getRedmineGatewayLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * gatewayの必須設定とsecretが読み込み済みか確認する
         * @description Redmine上流の疎通は再起動判定へ含めず、運用doctorで確認する。
         */
        get: operations["getRedmineGatewayReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 非公開browser profile UUIDからparticipant credentialを発行する */
        post: operations["createRedmineParticipant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 公開profileとcapabilityを取得する */
        get: operations["getRedmineProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/creation-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 投稿画面で有効な任意issue項目と選択肢を取得する */
        get: operations["getRedmineCreationOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 認証済みprincipalを取得する */
        get: operations["getRedmineCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 現在resourceまたはProfile内Workspaceのthreadを一覧する
         * @description scope省略時またはresourceではresourceKind、resourceKey、pageKeyが必須。
         *     scope=workspaceではこれら3項目を指定せず、Profileに固定されたWorkspace全体を一覧する。
         *     Origin検査はCSRF緩和であり利用者認証ではないため、Profileの公開範囲を閲覧境界として扱う。
         */
        get: operations["listRedmineThreads"];
        put?: never;
        /** Redmine issueとして初回投稿を作成する */
        post: operations["createRedmineThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/threads/{threadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全journalとattachmentを含むthreadを取得する */
        get: operations["getRedmineThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/threads/{threadId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redmine journalへ返信を追加する */
        post: operations["createRedmineMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profileId}/threads/{threadId}/messages/{messageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 自分の投稿を追記型edit journalで更新する */
        patch: operations["updateRedmineMessage"];
        trace?: never;
    };
    "/profiles/{profileId}/threads/{threadId}/attachments/{attachmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** thread所属確認済みattachmentを取得する */
        get: operations["getRedmineAttachment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            status: "ok";
        };
        HostResourceRef: {
            /** @constant */
            schemaVersion: "1";
            /** @enum {string} */
            kind: "record" | "page";
            key: string;
        };
        Perspective: {
            code: string;
            label: string;
        };
        CaptureProfile: {
            enabled: boolean;
            maximumUploadBytes: number;
            contentTypes: ("image/png" | "image/webp")[];
        };
        AttachmentProfile: {
            maximumInlinePreviewBytes: number;
            maximumDownloadBytes: number;
        };
        ClientProfile: {
            /** @constant */
            schemaVersion: "1";
            id: string;
            displayName: string;
            applicationKey: string;
            environmentKey: string;
            externalWorkspaceKey: string;
            perspectives: components["schemas"]["Perspective"][];
            capture: components["schemas"]["CaptureProfile"];
            attachments: components["schemas"]["AttachmentProfile"];
            showRedmineLink?: boolean;
        };
        Capabilities: {
            canRead: boolean;
            canCreate: boolean;
            canReply: boolean;
            canEditOwn: boolean;
            /** @constant */
            stateReadOnly: true;
        };
        ProfileResult: {
            profile: components["schemas"]["ClientProfile"];
            capabilities: components["schemas"]["Capabilities"];
        };
        Principal: {
            /** Format: uuid */
            participantId: string;
            displayName: string | null;
            /** @constant */
            source: "participant-credential";
        };
        CurrentUserResult: {
            principal: components["schemas"]["Principal"];
        };
        CreateParticipantRequest: {
            /** Format: uuid */
            browserProfileId: string;
        };
        ParticipantResult: {
            /** Format: uuid */
            participantId: string;
            credential: string;
        };
        NamedValue: {
            id: number;
            name: string;
        };
        /** @enum {string} */
        OptionalIssueField: "parent_issue" | "due_date" | "priority";
        CreationOptions: {
            optionalIssueFields: components["schemas"]["OptionalIssueField"][];
            priorities: components["schemas"]["NamedValue"][];
        };
        Locator: {
            /** @constant */
            v: "1";
            location: components["schemas"]["Location"];
            target: components["schemas"]["Target"] | null;
        };
        Location: {
            /** @constant */
            schemaVersion: "1";
            pageKey: string;
            routeTemplate: string;
            pathParameters: {
                [key: string]: string;
            };
            queryParameters?: {
                [key: string]: string;
            };
        };
        Target: components["schemas"]["UiElementTarget"] | components["schemas"]["ScreenPositionTarget"] | components["schemas"]["MapFeatureTarget"] | components["schemas"]["MapPositionTarget"] | components["schemas"]["CustomTarget"];
        UiElementTarget: {
            /** @constant */
            schemaVersion: "1";
            /** @constant */
            kind: "ui-element";
            elementKey: string;
            relativeX: number;
            relativeY: number;
        };
        ScreenPositionTarget: {
            /** @constant */
            schemaVersion: "1";
            /** @constant */
            kind: "screen-position";
            relativeX: number;
            relativeY: number;
        };
        MapFeatureTarget: {
            /** @constant */
            schemaVersion: "1";
            /** @constant */
            kind: "map-feature";
            /** @constant */
            provider: "maplibre";
            sourceKey: string;
            sourceLayer?: string;
            featureKey: string;
            longitude: number;
            latitude: number;
        };
        MapPositionTarget: {
            /** @constant */
            schemaVersion: "1";
            /** @constant */
            kind: "map-position";
            longitude: number;
            latitude: number;
        };
        CustomTarget: {
            /** @constant */
            schemaVersion: "1";
            /** @constant */
            kind: "custom";
            provider: string;
            targetKey: string;
            fallbackRelativeX: number;
            fallbackRelativeY: number;
            metadata?: {
                [key: string]: string | number | boolean | null;
            };
        };
        Attachment: {
            id: number;
            filename: string;
            byteSize: number;
            contentType: string | null;
            author: components["schemas"]["NamedValue"];
            /** Format: date-time */
            createdAt: string;
            inlinePreview: boolean;
            primaryEvidence: boolean;
        };
        Reply: {
            /** @constant */
            kind: "reply";
            journalId: number;
            body: string;
            author: components["schemas"]["NamedValue"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string | null;
            /** Format: uuid */
            messageId?: string;
            /** Format: uuid */
            participantId?: string | null;
            displayName?: string | null;
            version?: number;
            canEdit?: boolean;
            versions?: components["schemas"]["MessageVersion"][];
        };
        MessageVersion: {
            version: number;
            body: string;
            /** Format: date-time */
            editedAt: string;
        };
        MessageAuthor: {
            /** @enum {string} */
            kind: "participant" | "redmine";
            /** Format: uuid */
            participantId: string | null;
            displayName: string;
        };
        ConversationMessage: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "initial" | "reply";
            journalId: number | null;
            body: string;
            author: components["schemas"]["MessageAuthor"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            editedAt: string | null;
            version: number;
            versions: components["schemas"]["MessageVersion"][];
            canEdit: boolean;
        };
        Activity: {
            /** @constant */
            kind: "activity";
            journalId: number;
            /** @enum {string} */
            field: "status" | "assignee" | "priority" | "tracker" | "subject" | "description" | "attachment";
            oldValue: string | null;
            newValue: string | null;
            author: components["schemas"]["NamedValue"];
            /** Format: date-time */
            createdAt: string;
        };
        DiagnosticActivity: {
            /** @constant */
            kind: "diagnostic";
            journalId: number | null;
            message: string;
        };
        ThreadSummary: {
            /** Format: uuid */
            threadId: string;
            issueId: number;
            subject: string;
            initialComment: string;
            latestReply: string | null;
            status: components["schemas"]["NamedValue"];
            priority: components["schemas"]["NamedValue"] | null;
            assignee: components["schemas"]["NamedValue"] | null;
            author: components["schemas"]["NamedValue"];
            perspectiveCode: string | null;
            locator: components["schemas"]["Locator"] | null;
            hasAttachments: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            closed?: boolean;
        };
        Thread: {
            /** Format: uuid */
            threadId: string;
            issueId: number;
            subject: string;
            initialComment: string;
            latestReply: string | null;
            status: components["schemas"]["NamedValue"];
            priority: components["schemas"]["NamedValue"] | null;
            assignee: components["schemas"]["NamedValue"] | null;
            author: components["schemas"]["NamedValue"];
            perspectiveCode: string | null;
            locator: components["schemas"]["Locator"] | null;
            hasAttachments: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            description: string;
            closed?: boolean;
            tracker: components["schemas"]["NamedValue"];
            timeline: (components["schemas"]["Reply"] | components["schemas"]["Activity"] | components["schemas"]["DiagnosticActivity"])[];
            attachments: components["schemas"]["Attachment"][];
            /** Format: uri */
            redmineUrl: string | null;
            diagnosticCount: number;
            messages?: components["schemas"]["ConversationMessage"][];
        };
        ThreadListResult: {
            threads: components["schemas"]["ThreadSummary"][];
            totalCount: number;
            nextCursor: string | null;
        };
        ThreadResult: {
            thread: components["schemas"]["Thread"];
        };
        CreateThreadRequest: {
            resourceRef: components["schemas"]["HostResourceRef"];
            /** Format: uuid */
            threadId: string;
            /** Format: uuid */
            intentId: string;
            comment: string;
            perspectiveCode: string;
            location: components["schemas"]["Location"];
            target: components["schemas"]["Target"] | null;
            release: string;
            locale: string;
            /** Format: uri */
            threadUrl?: string | null;
            /** Format: date-time */
            capturedAt: string;
            evidence: components["schemas"]["EvidenceMetadata"] | null;
            participantName?: string | null;
            parentIssueId?: number;
            /** Format: date */
            dueDate?: string;
            priorityId?: number;
        };
        CreateMessageRequest: {
            /** Format: uuid */
            messageId: string;
            body: string;
            participantName: string | null;
        };
        UpdateMessageRequest: {
            body: string;
            expectedVersion: number;
            participantName: string | null;
        };
        EvidenceMetadata: {
            filename: string;
            /** @enum {string} */
            contentType: "image/png" | "image/webp";
            byteSize: number;
            sha256: string;
            viewportWidth: number;
            viewportHeight: number;
            pixelRatio: number;
            /** Format: date-time */
            capturedAt: string;
        };
        Problem: {
            /** @enum {string} */
            code: "redmine.unauthenticated" | "redmine.invalid_api_key" | "redmine.permission_denied" | "redmine.not_found" | "redmine.duplicate_thread_id" | "redmine.thread_mismatch" | "redmine.content_type_rejected" | "redmine.payload_too_large" | "redmine.validation_failed" | "redmine.rate_limited" | "redmine.unavailable" | "redmine.contract_invalid" | "feedback.locator_too_large";
            message: string;
            retryable: boolean;
            upstreamStatus?: number | null;
            /** Format: uuid */
            requestId: string;
        };
        ProblemEnvelope: {
            /** @constant */
            ok: false;
            error: components["schemas"]["Problem"];
        };
    };
    responses: {
        /** @description sanitize済みproblem */
        Problem: {
            headers: {
                "Cache-Control": components["headers"]["NoStore"];
                "X-Content-Type-Options": components["headers"]["NoSniff"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemEnvelope"];
            };
        };
    };
    parameters: {
        ProfileId: string;
        ThreadId: string;
        MessageId: string;
        AttachmentId: number;
        Origin: string;
        /** @description browserがGETへ付与した場合だけsame-origin一致を検証する */
        OriginRead: string;
        SecFetchSite: "same-origin";
        ParticipantCredential: string;
        IdempotencyKey: string;
        ResourceKind: "record" | "page";
        /** @description 省略時はresource。workspaceではProfile内Workspace全体を一覧する */
        ListScope: "resource" | "workspace";
        /** @description resource scopeでは必須、workspace scopeでは指定禁止 */
        ListResourceKind: "record" | "page";
        /** @description resource scopeでは必須、workspace scopeでは指定禁止 */
        ListResourceKey: string;
        /** @description resource scopeでは必須、workspace scopeでは指定禁止 */
        ListPageKey: string;
        ResourceKey: string;
        Sort: "created_desc" | "created_asc" | "updated_desc";
        StatusFilter: string;
        PerspectiveFilter: string;
        AssigneeFilter: number;
        PriorityFilter: number;
        QueryFilter: string;
        Cursor: string;
    };
    requestBodies: never;
    headers: {
        NoStore: "no-store";
        NoSniff: "nosniff";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRedmineGatewayLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description processはrequestを処理できる */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getRedmineGatewayReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description gatewayはFeedback requestを受け付けられる */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    createRedmineParticipant: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "Sec-Fetch-Site": components["parameters"]["SecFetchSite"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateParticipantRequest"];
            };
        };
        responses: {
            /** @description 発行したparticipant credential */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantResult"];
                };
            };
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    getRedmineProfile: {
        parameters: {
            query?: never;
            header: {
                /** @description browserがGETへ付与した場合だけsame-origin一致を検証する */
                Origin?: components["parameters"]["OriginRead"];
                "Sec-Fetch-Site": components["parameters"]["SecFetchSite"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 公開profile */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    getRedmineCreationOptions: {
        parameters: {
            query?: never;
            header: {
                /** @description browserがGETへ付与した場合だけsame-origin一致を検証する */
                Origin?: components["parameters"]["OriginRead"];
                "Sec-Fetch-Site": components["parameters"]["SecFetchSite"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任意issue項目と選択肢 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreationOptions"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    getRedmineCurrentUser: {
        parameters: {
            query?: never;
            header: {
                /** @description browserがGETへ付与した場合だけsame-origin一致を検証する */
                Origin?: components["parameters"]["OriginRead"];
                "Sec-Fetch-Site": components["parameters"]["SecFetchSite"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description current principal */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    listRedmineThreads: {
        parameters: {
            query: {
                /** @description 省略時はresource。workspaceではProfile内Workspace全体を一覧する */
                scope?: components["parameters"]["ListScope"];
                /** @description resource scopeでは必須、workspace scopeでは指定禁止 */
                resourceKind?: components["parameters"]["ListResourceKind"];
                /** @description resource scopeでは必須、workspace scopeでは指定禁止 */
                resourceKey?: components["parameters"]["ListResourceKey"];
                /** @description resource scopeでは必須、workspace scopeでは指定禁止 */
                pageKey?: components["parameters"]["ListPageKey"];
                sort: components["parameters"]["Sort"];
                status?: components["parameters"]["StatusFilter"];
                perspectiveCode?: components["parameters"]["PerspectiveFilter"];
                assigneeId?: components["parameters"]["AssigneeFilter"];
                priorityId?: components["parameters"]["PriorityFilter"];
                q?: components["parameters"]["QueryFilter"];
                cursor?: components["parameters"]["Cursor"];
            };
            header: {
                /** @description browserがGETへ付与した場合だけsame-origin一致を検証する */
                Origin?: components["parameters"]["OriginRead"];
                "Sec-Fetch-Site": components["parameters"]["SecFetchSite"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description thread一覧 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadListResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    createRedmineThread: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "Sec-Fetch-Site": components["parameters"]["SecFetchSite"];
                "X-Feedback-Participant-Credential": components["parameters"]["ParticipantCredential"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    request: components["schemas"]["CreateThreadRequest"];
                    /** Format: binary */
                    evidence?: string;
                };
            };
        };
        responses: {
            /** @description 冪等回収した既存thread */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadResult"];
                };
            };
            /** @description 作成したthread */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            406: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    getRedmineThread: {
        parameters: {
            query: {
                resourceKind: components["parameters"]["ResourceKind"];
                resourceKey: components["parameters"]["ResourceKey"];
            };
            header: {
                /** @description browserがGETへ付与した場合だけsame-origin一致を検証する */
                Origin?: components["parameters"]["OriginRead"];
                "Sec-Fetch-Site": components["parameters"]["SecFetchSite"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description thread詳細 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    createRedmineMessage: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "Sec-Fetch-Site": components["parameters"]["SecFetchSite"];
                "X-Feedback-Participant-Credential": components["parameters"]["ParticipantCredential"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMessageRequest"];
            };
        };
        responses: {
            /** @description 冪等回収後のthread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadResult"];
                };
            };
            /** @description 返信後のthread */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadResult"];
                };
            };
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    updateRedmineMessage: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "Sec-Fetch-Site": components["parameters"]["SecFetchSite"];
                "X-Feedback-Participant-Credential": components["parameters"]["ParticipantCredential"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
                threadId: components["parameters"]["ThreadId"];
                messageId: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMessageRequest"];
            };
        };
        responses: {
            /** @description 編集後のthread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadResult"];
                };
            };
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    getRedmineAttachment: {
        parameters: {
            query: {
                resourceKind: components["parameters"]["ResourceKind"];
                resourceKey: components["parameters"]["ResourceKey"];
            };
            header: {
                /** @description browserがGETへ付与した場合だけsame-origin一致を検証する */
                Origin?: components["parameters"]["OriginRead"];
                "Sec-Fetch-Site": components["parameters"]["SecFetchSite"];
            };
            path: {
                profileId: components["parameters"]["ProfileId"];
                threadId: components["parameters"]["ThreadId"];
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 検証済みattachment bytes */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    /** @description sanitize済みfilenameから生成したattachment disposition */
                    "Content-Disposition"?: string;
                    /** @description lowercase SHA-256 hex */
                    "X-Feedback-Content-SHA256"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                    "image/webp": string;
                    "application/octet-stream": string;
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            406: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
}
